# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-07-27 16:06:27
"""
import arcpy
from sys import argv

def Model1(Bridgman_OE_W_Segments="Bridgman_OE_W_Segments"):  # Probably an upland

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    Probably_an_upland_expression = "ATTRIBUTE <> 'U' And ACRES > 150"

    # Process: Select Layer By Attribute (Select Layer By Attribute) (management)
    Updated_Layer_Or_Table_View, Count = arcpy.management.SelectLayerByAttribute(in_layer_or_view=Bridgman_OE_W_Segments, selection_type="NEW_SELECTION", where_clause=Probably_an_upland_expression, invert_where_clause="")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\delenteny\Documents\ArcGIS\Projects\Dale_NWI\Dale_NWI.gdb", workspace=r"C:\Users\delenteny\Documents\ArcGIS\Projects\Dale_NWI\Dale_NWI.gdb"):
        Model1(*argv[1:])
